### ISSUE TITLE
suggestions for plotting

### ISSUE THREAD

**Issue by botteon** [JortBox/Halo-FDCA#4]
Hi, you could do the following edits to the code:

1) Symmetric color bar (centered on 0) for the residual image:
https://github.com/JortBox/Halo-FDCA/blob/caad4e5ce6ba01da2318cfc4f9e9bf3c3eb8646b/FDCA/plotting_fits.py#L92
--> `Normdiv = mplc.TwoSlopeNorm(vcenter=0., vmin=-2, vmax=2)`
 https://github.com/JortBox/Halo-FDCA/blob/caad4e5ce6ba01da2318cfc4f9e9bf3c3eb8646b/FDCA/plotting_fits.py#L94
 --> `Normdiv = mplc.TwoSlopeNorm(vcenter=0., vmin=-2, vmax=2)`

2) Contours levels spaced by a factor of 2, from 1sigma:
https://github.com/JortBox/Halo-FDCA/blob/caad4e5ce6ba01da2318cfc4f9e9bf3c3eb8646b/FDCA/plotting_fits.py#L99
--> `LEVEL = np.array([1,2,4,8,16,32,64,128,256,512,1024,2048,4096])*noise`

3) Increase the scalebar to 250 kpc (100 kpc is a bit too small):
https://github.com/JortBox/Halo-FDCA/blob/caad4e5ce6ba01da2318cfc4f9e9bf3c3eb8646b/FDCA/plotting_fits.py#L177
--> `asb = AnchoredSizeBar(ax.transData,length.value*2.5,`
https://github.com/JortBox/Halo-FDCA/blob/caad4e5ce6ba01da2318cfc4f9e9bf3c3eb8646b/FDCA/plotting_fits.py#L178
--> `r"250 kpc",`

**Comment by JortBox** [comment]
I have incorporated suggestion 2 and 3 now.
